### ISSUE TITLE
Hello, there are some questions

### ISSUE THREAD

**Issue by RoseLucy** [mir-pucrs/smartix-rl#13]
Hello, I would like to ask the previous database account and password are smartix, but the account and password of this database are dbuser and tpch.Thank you！
![1617177598(1)](https://user-images.githubusercontent.com/46710549/113111972-43041980-923b-11eb-8d1d-12145b42dfe5.png)

**Comment by gabrielplicks** [comment]
Hi! I'm sorry, the information in the README file is mostly outdated. I also haven't used MySQL anymore. In the current code, I've used Postgres and Hypo-pg extension for hypothetical indexes. Regarding the password, you can set any password you like :) i've just used words "smartix" or "dbuser" to make it easier. Let me know if you have any other questions :)

**Comment by RoseLucy** [comment]
Ok, I see, this means that these two are actually the same database, but the account and password are different? Thank you!
