### ISSUE TITLE
Hello, the comment just now was lost

### ISSUE THREAD

**Issue by RoseLucy** [mir-pucrs/smartix-rl#14]
Sorry that the comment disappeared just now. As you said, this means that the two are actually the same database, but the account and password are different? Thank you!

**Comment by meneguzzi** [comment]
This is what we wanted to solve with #12, please comment there any missing info to be documented.

**Comment by gabrielplicks** [comment]
Hi @RoseLucy , yes, the two are the same database :) the passwords should be the same. You can manage the database user anyway you like, as long as you set the credentials correctly in the code for the RL agent to have access to it.
