### ISSUE TITLE
Problem with hypopg_list_indexes

### ISSUE THREAD

**Issue by earthwuyang** [mir-pucrs/smartix-rl#16]
Hello, I meet an error that reports hypopg_list_indexes() is not function defined. And I find hypopg_list_indexes is a view.
Maybe this is due to new version of hypopg?

**Comment by gabrielplicks** [comment]
Hi! I've checked the documentation and the hypopg_list_indexes is still available in the current version of HypoPG. Indeed it is a view. I'm not sure how I can help you, but you can try to create again the HypoPG tables (or reinstall if it does not work after recreating them).
